# Generated by Django 2.1 on 2020-07-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HspApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.IntegerField(default=123456789, unique=True),
        ),
    ]
