# Generated by Django 2.1 on 2020-07-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HspApp', '0003_auto_20200723_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.IntegerField(default=123456789),
        ),
    ]
