# Generated by Django 2.1 on 2020-07-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HspApp', '0004_auto_20200723_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(max_length=13),
        ),
    ]
